## makeCacheMatrix takes in a matrix as parameter and defines and returns 
## the functions needed to implement the caching of the matrix inverse, 
## in order to save computation power and time when repeatedly inverting 
## the same matrix
## casheSolve takes as parameter a list of the functions generated by 
## makeCacheMatrix and uses them to return the inverse matrix




## takes in a matrix, returns a list of getters and setters of x and its inverse.
makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y){
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInverse <- function(solveMatrix) inv <<- solveMatrix
  getInverse <- function() inv
  list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}


## cacheSolve takes in a matrix x, and returns a cashed version 
## of the inverse of x if it is already stored in x, 
## otherwise creates the inverse matrix, saves a cached copy of it in x, 
## and returns it.
cacheSolve <- function(x, ...) {

  inv <- x$getInverse()
  
  
  # if the inverse matrix was not already calculated and cached, 
  # create the inverse, cache it, and return it
  if(is.null(inv))
  {
    data <- x$get()
    inv <- solve(data)
    x$setInverse(inv)
  }
  # if the inverse matrix was already calculated and cached, 
  # print a message that you are returning a cached version 
  else
  {
    message("getting cached data")
  }
  
  return(inv)      
  
}





